name: camera_web
description: A Flutter plugin for getting information about and controlling the camera on Web.
version: 0.3.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: camera
    platforms:
      web:
        pluginClass: CameraPlugin
        fileName: camera_web.dart

dependencies:
  camera_platform_interface:
    path: ../../packages/camera_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
