name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
version: 0.10.0
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

dependencies:
  camera_android: 
    path: ./packages/camera_android
  camera_avfoundation: 
    path: ./packages/camera_avfoundation
  camera_platform_interface: 
    path: ./packages/camera_platform_interface
  camera_web: 
    path: ./packages/camera_web
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  quiver: ^3.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  video_player: ^2.0.0

dependency_overrides: 
  camera_android:
    path: packages/camera_android
  camera_avfoundation:
    path: packages/camera_avfoundation
  camera_platform_interface:
    path: packages/camera_platform_interface
  camera_web:
    path: packages/camera_web
