name: camera_platform_interface
description: A common platform interface for the camera plugin.
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.8.0"

dependencies:
  cross_file: ^0.3.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
